version: "3.8"

services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'container_db'
    ports:
      - 27017:27017
#    environment:
#      - MYSQL_DATABASE=food_techchallenge
#      - MYSQL_PASSWORD=170593
#      - MYSQL_ROOT_PASSWORD=170593
    networks:
      - rede
    volumes:
      - ~/mongo/mongo:/var/lib/mongo

  spring-app:
    build:
      context: ./
    image: "pctheone/producao_ms_techchallenge:latest"
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - rede
    depends_on:
      - mongodb
    volumes:
      - .m2:/root/.m2
networks:
  rede: