version: "3.8"

services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'container_db'
    ports:
      - 27017:27017
#    environment:
#      - MYSQL_DATABASE=food_techchallenge
#      - MYSQL_PASSWORD=170593
#      - MYSQL_ROOT_PASSWORD=170593
    networks:
      - rede
    volumes:
      - ~/mongo/mongo:/var/lib/mongo

  spring-app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/food_techchallenge?createDatabaseIfNotExist=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 170593
    networks:
      - rede
    depends_on:
      - mongodb
    volumes:
      - .m2:/root/.m2
networks:
  rede: